
Q1. Student Performance DataFrame: Construction and Analysis
A college wants to analyze student performance using the following data.

In [42]:
import pandas as pd 


df= data = {    "Student_ID": [        101, 102, 103, 104, 105, 106,        107, 108, 109, 110, 111, 112    ],   
 "Name": [        "Amit", "Priya", "Rahul", "Neha",        "Vikas", "Pooja", "Karan", "Simran",        "Arjun", "Meena", "Rohit", "Anjali"    ],  
   "Age": [        19, 20, 18, 21, 20, 19,        22, 18, 21, 20, 19, 22    ],    
   "Hours_Studied": [        2, 5, 3, 8, 6, 4,        9, 2, 7, 5, 6, 8    ], 
      "Attendance": [        65, 85, 70, 95, 88, 75,        98, 60, 90, 82, 86, 94    ],  
        "Marks": [        48, 78, 55, 92, 84, 67,        96, 45, 89, 76, 81, 93    ]}

df=pd.DataFrame(data)

In [43]:
df

    Student_ID    Name  Age  Hours_Studied  Attendance  Marks
0          101    Amit   19              2          65     48
1          102   Priya   20              5          85     78
2          103   Rahul   18              3          70     55
3          104    Neha   21              8          95     92
4          105   Vikas   20              6          88     84
5          106   Pooja   19              4          75     67
6          107   Karan   22              9          98     96
7          108  Simran   18              2          60     45
8          109   Arjun   21              7          90     89
9          110   Meena   20              5          82     76
10         111   Rohit   19              6          86     81
11         112  Anjali   22              8          94     93

1.  Create a DataFrame and display its first five and last three records.

In [44]:
df.head()

   Student_ID   Name  Age  Hours_Studied  Attendance  Marks
0         101   Amit   19              2          65     48
1         102  Priya   20              5          85     78
2         103  Rahul   18              3          70     55
3         104   Neha   21              8          95     92
4         105  Vikas   20              6          88     84

In [45]:
df.tail(3)

    Student_ID    Name  Age  Hours_Studied  Attendance  Marks
9          110   Meena   20              5          82     76
10         111   Rohit   19              6          86     81
11         112  Anjali   22              8          94     93

2.  Determine the number of rows and columns programmatically. Verify that the result matches the expected dimensions.

In [46]:
print('dataset shape:',df.shape)
print('numbers of rows', df.shape[0])
print('number of columns',df.shape[1])

dataset shape: (12, 6)
numbers of rows 12
number of columns 6

3.  Extract all column names as a Python list and classify them as identifiers, categorical attributes, or numerical attributes.

In [47]:
df.columns

Index(['Student_ID', 'Name', 'Age', 'Hours_Studied', 'Attendance', 'Marks'], dtype='object')

In [48]:
df.select_dtypes(exclude='object')

    Student_ID  Age  Hours_Studied  Attendance  Marks
0          101   19              2          65     48
1          102   20              5          85     78
2          103   18              3          70     55
3          104   21              8          95     92
4          105   20              6          88     84
5          106   19              4          75     67
6          107   22              9          98     96
7          108   18              2          60     45
8          109   21              7          90     89
9          110   20              5          82     76
10         111   19              6          86     81
11         112   22              8          94     93

In [49]:
df.select_dtypes(include='object')

      Name
0     Amit
1    Priya
2    Rahul
3     Neha
4    Vikas
5    Pooja
6    Karan
7   Simran
8    Arjun
9    Meena
10   Rohit
11  Anjali

4.  Select the Name, Hours_Studied, and Marks columns. Then identify students whose marks are above the dataset's average.

In [50]:
import pandas as pd 


selected_data=df[['Name','Hours_Studied','Marks']]

average_marks=df['Marks'].mean()

print('average_marks:',average_marks)

above_average=selected_data[selected_data['Marks']>average_marks]
print(above_average)

average_marks: 75.33333333333333
      Name  Hours_Studied  Marks
1    Priya              5     78
3     Neha              8     92
4    Vikas              6     84
6    Karan              9     96
8    Arjun              7     89
9    Meena              5     76
10   Rohit              6     81
11  Anjali              8     93

5.  Reset the index after filtering, compare the original and new indices, and explain why an index should not automatically be treated as a student's unique identifier.

In [51]:
print(above_average)

      Name  Hours_Studied  Marks
1    Priya              5     78
3     Neha              8     92
4    Vikas              6     84
6    Karan              9     96
8    Arjun              7     89
9    Meena              5     76
10   Rohit              6     81
11  Anjali              8     93

In [53]:
reset_data=above_average.reset_index()
print(reset_data)

   index    Name  Hours_Studied  Marks
0      1   Priya              5     78
1      3    Neha              8     92
2      4   Vikas              6     84
3      6   Karan              9     96
4      8   Arjun              7     89
5      9   Meena              5     76
6     10   Rohit              6     81
7     11  Anjali              8     93

In [54]:
print('original indices:')
print(above_average.index.tolist())

print('new indices:')
print(reset_data.index.to_list())

original indices:
[1, 3, 4, 6, 8, 9, 10, 11]
new indices:
[0, 1, 2, 3, 4, 5, 6, 7]

Q2. Advanced Row and Column Selection Using iloc and loc
Using the DataFrame created in Q1, perform the following operations.

1.  Select rows at positions 2 through 7 using iloc, returning only Name, Attendance, and Marks. Explain why the ending position behaves differently from the equivalent label-based selection.

In [56]:
selected_rows=df.iloc[2:8][['Name','Attendance','Marks']]
print(selected_rows)

     Name  Attendance  Marks
2   Rahul          70     55
3    Neha          95     92
4   Vikas          88     84
5   Pooja          75     67
6   Karan          98     96
7  Simran          60     45

In [58]:
print(df.iloc[2:8])

print(df.loc[2:8])

   Student_ID    Name  Age  Hours_Studied  Attendance  Marks
2         103   Rahul   18              3          70     55
3         104    Neha   21              8          95     92
4         105   Vikas   20              6          88     84
5         106   Pooja   19              4          75     67
6         107   Karan   22              9          98     96
7         108  Simran   18              2          60     45
   Student_ID    Name  Age  Hours_Studied  Attendance  Marks
2         103   Rahul   18              3          70     55
3         104    Neha   21              8          95     92
4         105   Vikas   20              6          88     84
5         106   Pooja   19              4          75     67
6         107   Karan   22              9          98     96
7         108  Simran   18              2          60     45
8         109   Arjun   21              7          90     89