
Q1. Student Performance DataFrame: Construction and Analysis
A college wants to analyze student performance using the following data.

In [137]:
import pandas as pd 


df= data = {    "Student_ID": [        101, 102, 103, 104, 105, 106,        107, 108, 109, 110, 111, 112    ],   
 "Name": [        "Amit", "Priya", "Rahul", "Neha",        "Vikas", "Pooja", "Karan", "Simran",        "Arjun", "Meena", "Rohit", "Anjali"    ],  
   "Age": [        19, 20, 18, 21, 20, 19,        22, 18, 21, 20, 19, 22    ],    
   "Hours_Studied": [        2, 5, 3, 8, 6, 4,        9, 2, 7, 5, 6, 8    ], 
      "Attendance": [        65, 85, 70, 95, 88, 75,        98, 60, 90, 82, 86, 94    ],  
        "Marks": [        48, 78, 55, 92, 84, 67,        96, 45, 89, 76, 81, 93    ]}

df=pd.DataFrame(data)

In [138]:
df

    Student_ID    Name  Age  Hours_Studied  Attendance  Marks
0          101    Amit   19              2          65     48
1          102   Priya   20              5          85     78
2          103   Rahul   18              3          70     55
3          104    Neha   21              8          95     92
4          105   Vikas   20              6          88     84
5          106   Pooja   19              4          75     67
6          107   Karan   22              9          98     96
7          108  Simran   18              2          60     45
8          109   Arjun   21              7          90     89
9          110   Meena   20              5          82     76
10         111   Rohit   19              6          86     81
11         112  Anjali   22              8          94     93

1.  Create a DataFrame and display its first five and last three records.

In [139]:
df.head()

   Student_ID   Name  Age  Hours_Studied  Attendance  Marks
0         101   Amit   19              2          65     48
1         102  Priya   20              5          85     78
2         103  Rahul   18              3          70     55
3         104   Neha   21              8          95     92
4         105  Vikas   20              6          88     84

In [140]:
df.tail(3)

    Student_ID    Name  Age  Hours_Studied  Attendance  Marks
9          110   Meena   20              5          82     76
10         111   Rohit   19              6          86     81
11         112  Anjali   22              8          94     93

2.  Determine the number of rows and columns programmatically. Verify that the result matches the expected dimensions.

In [141]:
print('dataset shape:',df.shape)
print('numbers of rows', df.shape[0])
print('number of columns',df.shape[1])

dataset shape: (12, 6)
numbers of rows 12
number of columns 6

3.  Extract all column names as a Python list and classify them as identifiers, categorical attributes, or numerical attributes.

In [142]:
df.columns

Index(['Student_ID', 'Name', 'Age', 'Hours_Studied', 'Attendance', 'Marks'], dtype='object')

In [143]:
df.select_dtypes(exclude='object')

    Student_ID  Age  Hours_Studied  Attendance  Marks
0          101   19              2          65     48
1          102   20              5          85     78
2          103   18              3          70     55
3          104   21              8          95     92
4          105   20              6          88     84
5          106   19              4          75     67
6          107   22              9          98     96
7          108   18              2          60     45
8          109   21              7          90     89
9          110   20              5          82     76
10         111   19              6          86     81
11         112   22              8          94     93

In [144]:
df.select_dtypes(include='object')

      Name
0     Amit
1    Priya
2    Rahul
3     Neha
4    Vikas
5    Pooja
6    Karan
7   Simran
8    Arjun
9    Meena
10   Rohit
11  Anjali

4.  Select the Name, Hours_Studied, and Marks columns. Then identify students whose marks are above the dataset's average.

In [145]:
import pandas as pd 


selected_data=df[['Name','Hours_Studied','Marks']]

average_marks=df['Marks'].mean()

print('average_marks:',average_marks)

above_average=selected_data[selected_data['Marks']>average_marks]
print(above_average)

average_marks: 75.33333333333333
      Name  Hours_Studied  Marks
1    Priya              5     78
3     Neha              8     92
4    Vikas              6     84
6    Karan              9     96
8    Arjun              7     89
9    Meena              5     76
10   Rohit              6     81
11  Anjali              8     93

5.  Reset the index after filtering, compare the original and new indices, and explain why an index should not automatically be treated as a student's unique identifier.

In [146]:
print(above_average)

      Name  Hours_Studied  Marks
1    Priya              5     78
3     Neha              8     92
4    Vikas              6     84
6    Karan              9     96
8    Arjun              7     89
9    Meena              5     76
10   Rohit              6     81
11  Anjali              8     93

In [147]:
reset_data=above_average.reset_index()
print(reset_data)

   index    Name  Hours_Studied  Marks
0      1   Priya              5     78
1      3    Neha              8     92
2      4   Vikas              6     84
3      6   Karan              9     96
4      8   Arjun              7     89
5      9   Meena              5     76
6     10   Rohit              6     81
7     11  Anjali              8     93

In [148]:
print('original indices:')
print(above_average.index.tolist())

print('new indices:')
print(reset_data.index.to_list())

original indices:
[1, 3, 4, 6, 8, 9, 10, 11]
new indices:
[0, 1, 2, 3, 4, 5, 6, 7]

Q2. Advanced Row and Column Selection Using iloc and loc
Using the DataFrame created in Q1, perform the following operations.

1.  Select rows at positions 2 through 7 using iloc, returning only Name, Attendance, and Marks. Explain why the ending position behaves differently from the equivalent label-based selection.

In [149]:
selected_rows=df.iloc[2:8][['Name','Attendance','Marks']]
print(selected_rows)

     Name  Attendance  Marks
2   Rahul          70     55
3    Neha          95     92
4   Vikas          88     84
5   Pooja          75     67
6   Karan          98     96
7  Simran          60     45

In [150]:
print(df.iloc[2:8])

print(df.loc[2:8])

   Student_ID    Name  Age  Hours_Studied  Attendance  Marks
2         103   Rahul   18              3          70     55
3         104    Neha   21              8          95     92
4         105   Vikas   20              6          88     84
5         106   Pooja   19              4          75     67
6         107   Karan   22              9          98     96
7         108  Simran   18              2          60     45
   Student_ID    Name  Age  Hours_Studied  Attendance  Marks
2         103   Rahul   18              3          70     55
3         104    Neha   21              8          95     92
4         105   Vikas   20              6          88     84
5         106   Pooja   19              4          75     67
6         107   Karan   22              9          98     96
7         108  Simran   18              2          60     45
8         109   Arjun   21              7          90     89

2.  Create a copy of the DataFrame and set Student_ID as its index. Use loc to retrieve students with IDs 103, 107, and 110.

In [151]:
df_copy=df.copy()

In [152]:
df_copy=df_copy.set_index('Student_ID')

In [153]:
student_selected=df_copy.loc[[103,107,110]]

In [154]:
print(student_selected)

             Name  Age  Hours_Studied  Attendance  Marks
Student_ID
103         Rahul   18              3          70     55
107         Karan   22              9          98     96
110         Meena   20              5          82     76

3.  Using Boolean conditions, identify students who studied at least 6 hours, have attendance of at least 85%, and scored more than 80 marks.

In [155]:
result=df[
    (df['Hours_Studied']>=6)&
    (df['Attendance']>=85)&
    (df['Marks']>80)
]

print(result)

    Student_ID    Name  Age  Hours_Studied  Attendance  Marks
3          104    Neha   21              8          95     92
4          105   Vikas   20              6          88     84
6          107   Karan   22              9          98     96
8          109   Arjun   21              7          90     89
10         111   Rohit   19              6          86     81
11         112  Anjali   22              8          94     93

4.  Using iloc, extract the last four students and the last three columns without writing any column names explicitly.

In [156]:
result=df.iloc[-4:,-3:]
print(result)

    Hours_Studied  Attendance  Marks
8               7          90     89
9               5          82     76
10              6          86     81
11              8          94     93

5.  Create a new DataFrame containing students whose marks are below the median. Preserve their original student IDs and explain why filtering rows and resetting the index can produce different index labels.

In [157]:
median_marks=df['Marks'].median()
print('median_marks: ',median_marks)

below_median=df[df['Marks']< median_marks].copy()
print('below_median:',below_median)

median_marks:  79.5
below_median:    Student_ID    Name  Age  Hours_Studied  Attendance  Marks
0         101    Amit   19              2          65     48
1         102   Priya   20              5          85     78
2         103   Rahul   18              3          70     55
5         106   Pooja   19              4          75     67
7         108  Simran   18              2          60     45
9         110   Meena   20              5          82     76

Q3. Series vs. DataFrame: Feature Selection and Validation
A machine learning team wants to predict student marks using study hours and attendance.

Use the following dataset:

1.  Create X_single using only Hours_Studied and y using Marks. Demonstrate the difference between selecting the feature with single and double square brackets using type(), shape, and the resulting structure.

In [158]:
single=df['Hours_Studied']

x_Single=df[['Hours_Studied']]

y=df['Marks']



print('single bracket type:' ,type(single))
print('Double bracket type:',type(X_single))
print('target y type:',type(y))


print('single bracket shape:',single.shape)
print('Double bracket shape: ',X_single.shape)
print('target y shape:',y.shape)


print('\nsingle bracket output:')
print(single)


print('\nDouble bracket output:')
print(X_single)

print('\n target y:')
print(y)

single bracket type: <class 'pandas.core.series.Series'>
Double bracket type: <class 'pandas.core.frame.DataFrame'>
target y type: <class 'pandas.core.series.Series'>
single bracket shape: (12,)
Double bracket shape:  (12, 1)
target y shape: (12,)

single bracket output:
0     2
1     5
2     3
3     8
4     6
5     4
6     9
7     2
8     7
9     5
10    6
11    8
Name: Hours_Studied, dtype: int64

Double bracket output:
    Hours_Studied
0               2
1               5
2               3
3               8
4               6
5               4
6               9
7               2
8               7
9               5
10              6
11              8

 target y:
0     48
1     78
2     55
3     92
4     84
5     67
6     96
7     45
8     89
9     76
10    81
11    93
Name: Marks, dtype: int64

2.  Create X_multi using Hours_Studied, Attendance, and Sleep_Hours. Verify that Marks and Student_ID are excluded from the feature set.

In [159]:
print(df.columns.tolist())

['Student_ID', 'Name', 'Age', 'Hours_Studied', 'Attendance', 'Marks']

In [160]:
df['sleep_hours']=[7,8,7,6,5,8,9,9,9,8,7,6]

In [161]:
x_multi=df[['Hours_Studied','Attendance','sleep_hours']]
print(x_multi)

    Hours_Studied  Attendance  sleep_hours
0               2          65            7
1               5          85            8
2               3          70            7
3               8          95            6
4               6          88            5
5               4          75            8
6               9          98            9
7               2          60            9
8               7          90            9
9               5          82            8
10              6          86            7
11              8          94            6

In [162]:
print('feature columns:',x_multi.columns.tolist())
print('shape',x_multi.shape)

print('marks excluded:','Marks' not in x_multi.columns)
print('student ID excluded:','Student ID' not in x_multi.columns)

feature columns: ['Hours_Studied', 'Attendance', 'sleep_hours']
shape (12, 3)
marks excluded: True
student ID excluded: True

3.  Use drop() to construct features and target variables. Verify programmatically that no target column remains in X.

In [163]:
X=df.drop(columns=['Marks'])

y=df['Marks']

print('features (X):')
print(X.head())

print('\n Target (y):')
print(y.head())


print('\n is Marks present in X?', 'Marks' in X.columns)
assert 'Marks' not in X.columns, 'Target columns is still present in x'
print('verification successful: Marks is excluded from X')

features (X):
   Student_ID   Name  Age  Hours_Studied  Attendance  sleep_hours
0         101   Amit   19              2          65            7
1         102  Priya   20              5          85            8
2         103  Rahul   18              3          70            7
3         104   Neha   21              8          95            6
4         105  Vikas   20              6          88            5

 Target (y):
0    48
1    78
2    55
3    92
4    84
Name: Marks, dtype: int64

 is Marks present in X? False
verification successful: Marks is excluded from X

4.  Write validation code that checks whether X and y contain the same number of observations, whether X has the intended number of features, and whether the target is one-dimensional.

In [171]:
X.shape[0]==y.shape[0]

True

In [166]:
y.size

12

In [167]:
X.ndim

2

In [168]:
y.ndim

1

5. Explain why including Student_ID as a predictive feature may be inappropriate, even though it contains numerical values. Support your explanation with a comparison of the feature sets.

In [173]:
x_with_id=df.drop(columns=['Marks'])
x_without_id=df.drop(columns=['Marks','Student_ID'])


print('features with Student_ID:')
print(x_with_id.columns.tolist())


print('\n features without Student_ID:')
print(x_without_id.columns.tolist())


print('\n Shape with Student_ID',x_with_id.shape)
print('shape without student_ID',x_without_id.shape)

features with Student_ID:
['Student_ID', 'Name', 'Age', 'Hours_Studied', 'Attendance', 'sleep_hours']

 features without Student_ID:
['Name', 'Age', 'Hours_Studied', 'Attendance', 'sleep_hours']

 Shape with Student_ID (12, 6)
shape without student_ID (12, 5)

Q4. End-to-End Data Preparation Challenge
A training institute wants to predict students' final examination marks using their study behavior and attendance.

In [ ]:
1.  Inspect the DataFrame and write a reusable function that reports the number of rows, columns, column names, data types, and missing values. 
    The function must work with other DataFrames too.

In [175]:
import pandas as pd 

def inspect_dataframe(data):

 print('number of rows',data.shape[0]) 
 print('number of columns',data.shape[1])

 print('\n columns names')
 print(data.dtypes)

 print('\n missing values per column')
 print(data.isnull().sum())

 print('\n total missing values',data.isnull().sum().sum())

inspect_dataframe(df)

number of rows 12
number of columns 7

 columns names
Student_ID        int64
Name             object
Age               int64
Hours_Studied     int64
Attendance        int64
Marks             int64
sleep_hours       int64
dtype: object

 missing values per column
Student_ID       0
Name             0
Age              0
Hours_Studied    0
Attendance       0
Marks            0
sleep_hours      0
dtype: int64

 total missing values 0

2.  Build two feature sets: one using only Hours_Studied, and another using Hours_Studied, Attendance, and Sleep_Hours. Use Final_Marks as the target in both cases. Compare their dimensions and explain the difference between single-feature and multi-feature learning.

In [184]:
X_single=df[['Hours_Studied']]
X_multi=df[['Hours_Studied','Attendance',]]

y=df['Marks']

print('single feature shape',X_single.shape)
print('multi feature shape',X_multi.shape)
print('target shape',y.shape)


print('final marks in X_single','Marks' in X_single.columns)
print('final marks in X_multi', 'Marks' in X_multi.columns)

single feature shape (12, 1)
multi feature shape (12, 2)
target shape (12,)
final marks in X_single False
final marks in X_multi False

3.  Filter students with attendance below 70, then select their names, IDs, and marks. Preserve the student IDs after filtering and explain how the index differs from the ID.

In [188]:
low_attendance=df[df['Attendance']<70]
result=low_attendance[['Name','Student_ID','Marks']]
print(result)

     Name  Student_ID  Marks
0    Amit         101     48
7  Simran         108     45

4.  Create a reproducible 20% test split for the multi-feature dataset. Verify that the training and testing indices do not overlap and that all four outputs have consistent dimensions.

In [194]:
from sklearn.model_selection import train_test_split


X_multi = df[['Hours_Studied', 'Attendance']]
y = df['Marks']

X_train, X_test, y_train, y_test = train_test_split(
    X_multi,
    y,
    test_size=0.20,
    random_state=42
)

print("X_train shape:", X_train.shape)
print("X_test shape:", X_test.shape)
print("y_train shape:", y_train.shape)
print("y_test shape:", y_test.shape)


print("Training and testing indices overlap:",
      len(set(X_train.index) & set(X_test.index)) > 0)

print("Training dimensions consistent:",
      len(X_train) == len(y_train))



print("Testing dimensions consistent:",
      len(X_test) == len(y_test))

X_train shape: (9, 2)
X_test shape: (3, 2)
y_train shape: (9,)
y_test shape: (3,)
Training and testing indices overlap: False
Training dimensions consistent: True
Testing dimensions consistent: True

5.  Develop a complete data-preparation pipeline in Python that creates the DataFrame, validates the feature and target columns, generates the train-test split, and prints a concise report of the resulting datasets. Explain two potential mistakes that could make the pipeline unreliable.

In [195]:
import pandas as pd
from sklearn.model_selection import train_test_split

# Step 1: Create the DataFrame
data = {
    'Student_ID': [101, 102, 103, 104, 105, 106,
                   107, 108, 109, 110, 111, 112],
    'Name': ['Amit', 'Priya', 'Rahul', 'Neha', 'Vikas', 'Pooja',
             'Karan', 'Simran', 'Arjun', 'Meena', 'Rohit', 'Anjali'],
    'Age': [19, 20, 18, 21, 20, 19, 22, 18, 21, 20, 19, 22],
    'Hours_Studied': [2, 5, 3, 8, 6, 4, 9, 2, 7, 5, 6, 8],
    'Attendance': [65, 85, 70, 95, 88, 75, 98, 60, 90, 82, 86, 94],
    'Marks': [48, 78, 55, 92, 84, 67, 96, 45, 89, 76, 81, 93]
}

df = pd.DataFrame(data)

# Step 2: Define features and target
feature_columns = ['Hours_Studied', 'Attendance']
target_column = 'Marks'

# Step 3: Validate required columns
required_columns = feature_columns + [target_column]

missing_columns = [
    col for col in required_columns
    if col not in df.columns
]

if missing_columns:
    raise ValueError(f"Missing columns: {missing_columns}")

# Check for missing values
if df[required_columns].isnull().any().any():
    raise ValueError("Missing values found in features or target.")

# Check that feature and target values are numeric
if not all(
    pd.api.types.is_numeric_dtype(df[col])
    for col in required_columns
):
    raise TypeError("Features and target must be numeric.")

# Step 4: Create X and y
X = df[feature_columns]
y = df[target_column]

# Step 5: Generate reproducible train-test split
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.20,
    random_state=42
)

# Step 6: Print a concise report
print("===== DATA PREPARATION REPORT =====")
print("Original DataFrame:", df.shape)
print("Features:", feature_columns)
print("Target:", target_column)

print("\nTraining features:", X_train.shape)
print("Testing features:", X_test.shape)
print("Training target:", y_train.shape)
print("Testing target:", y_test.shape)

print("\nTraining dimensions consistent:",
      len(X_train) == len(y_train))

print("Testing dimensions consistent:",
      len(X_test) == len(y_test))

print("Index overlap:",
      not set(X_train.index).isdisjoint(set(X_test.index)))

print("\nPipeline completed successfully!")

===== DATA PREPARATION REPORT =====
Original DataFrame: (12, 6)
Features: ['Hours_Studied', 'Attendance']
Target: Marks

Training features: (9, 2)
Testing features: (3, 2)
Training target: (9,)
Testing target: (3,)

Training dimensions consistent: True
Testing dimensions consistent: True
Index overlap: False

Pipeline completed successfully!