In [1]:
import pandas as pd

data = {
    'Age': [22, 25, 28, 30, 35, 24, 32, 27, 29, 26],
    'Salary': [25000, 35000, 45000, 55000, 75000,
               30000, 60000, 40000, 50000, 32000],
    'Experience': [1, 2, 4, 6, 10, 1, 7, 3, 5, 2],
    'Gender': ['Male', 'Female', 'Male', 'Female', 'Male',
               'Female', 'Male', 'Female', 'Male', 'Female'],
    'Department': ['IT', 'HR', 'Finance', 'IT', 'Marketing',
                   'HR', 'IT', 'Finance', 'Marketing', 'IT'],
    'City': ['Bhopal', 'Indore', 'Delhi', 'Mumbai', 'Pune',
             'Bhopal', 'Delhi', 'Indore', 'Pune', 'Mumbai']
}

df = pd.DataFrame(data)

print(df)

   Age  Salary  Experience  Gender Department    City
0   22   25000           1    Male         IT  Bhopal
1   25   35000           2  Female         HR  Indore
2   28   45000           4    Male    Finance   Delhi
3   30   55000           6  Female         IT  Mumbai
4   35   75000          10    Male  Marketing    Pune
5   24   30000           1  Female         HR  Bhopal
6   32   60000           7    Male         IT   Delhi
7   27   40000           3  Female    Finance  Indore
8   29   50000           5    Male  Marketing    Pune
9   26   32000           2  Female         IT  Mumbai

In [2]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Age         10 non-null     int64
 1   Salary      10 non-null     int64
 2   Experience  10 non-null     int64
 3   Gender      10 non-null     object
 4   Department  10 non-null     object
 5   City        10 non-null     object
dtypes: int64(3), object(3)
memory usage: 612.0+ bytes

In [4]:
df.shape

(10, 6)

In [5]:
df['Age']

0    22
1    25
2    28
3    30
4    35
5    24
6    32
7    27
8    29
9    26
Name: Age, dtype: int64

In [6]:
for i in df ['Age']:
    print(i)

22
25
28
30
35
24
32
27
29
26

In [7]:
df[['Age','Gender']]

   Age  Gender
0   22    Male
1   25  Female
2   28    Male
3   30  Female
4   35    Male
5   24  Female
6   32    Male
7   27  Female
8   29    Male
9   26  Female

In [9]:
df.select_dtypes(exclude='object')

   Age  Salary  Experience
0   22   25000           1
1   25   35000           2
2   28   45000           4
3   30   55000           6
4   35   75000          10
5   24   30000           1
6   32   60000           7
7   27   40000           3
8   29   50000           5
9   26   32000           2

In [10]:
df.select_dtypes(include='object')

   Gender Department    City
0    Male         IT  Bhopal
1  Female         HR  Indore
2    Male    Finance   Delhi
3  Female         IT  Mumbai
4    Male  Marketing    Pune
5  Female         HR  Bhopal
6    Male         IT   Delhi
7  Female    Finance  Indore
8    Male  Marketing    Pune
9  Female         IT  Mumbai

In [11]:
df.columns

Index(['Age', 'Salary', 'Experience', 'Gender', 'Department', 'City'], dtype='object')

In [15]:
df.select_dtypes(include='object').columns

Index(['Gender', 'Department', 'City'], dtype='object')

In [16]:
df.loc[3]

Age               30
Salary         55000
Experience         6
Gender        Female
Department        IT
City          Mumbai
Name: 3, dtype: object

In [19]:
df.loc[3,'City']

'Mumbai'

In [23]:
df.loc[[2,3,4],['City','Age']]

     City  Age
2   Delhi   28
3  Mumbai   30
4    Pune   35

df.loc[[2,3,4],[City,Age]]

In [26]:
df.iloc[[2,3,4],[2,3,4]]

   Experience  Gender Department
2           4    Male    Finance
3           6  Female         IT
4          10    Male  Marketing

In [31]:
df.idxmax(axis=0)

Age           4
Salary        4
Experience    4
Gender        0
Department    4
City          4
dtype: int64

In [45]:
avg_salary=df.groupby('Department')['Salary'].mean()
print(avg_salary)

Department
Finance      42500.0
HR           32500.0
IT           43000.0
Marketing    62500.0
Name: Salary, dtype: float64

In [47]:
df.groupby('Gender')['Salary'].agg(['min','max'])

          min    max
Gender
Female  30000  55000
Male    25000  75000

In [48]:
df

   Age  Salary  Experience  Gender Department    City
0   22   25000           1    Male         IT  Bhopal
1   25   35000           2  Female         HR  Indore
2   28   45000           4    Male    Finance   Delhi
3   30   55000           6  Female         IT  Mumbai
4   35   75000          10    Male  Marketing    Pune
5   24   30000           1  Female         HR  Bhopal
6   32   60000           7    Male         IT   Delhi
7   27   40000           3  Female    Finance  Indore
8   29   50000           5    Male  Marketing    Pune
9   26   32000           2  Female         IT  Mumbai

In [49]:
x=df[['Age', 'Salary', 'Experience', 'Gender', 'Department', 'City']]  #indipendent variable
y=df['Salary'] #dependent variable